### ISSUE TITLE
Doesn't works with all methods

### ISSUE THREAD

**Issue by ChoiZ** [e00E/lets-encrypt-icecast#2]
```
$ letsencrypt -t -i letsencrypt-icecast:icecast_installer run

How would you like to authenticate with the Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Place files in webroot directory (webroot)
2: Automatically use a temporary webserver (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
The letsencrypt-icecast:icecast_installer plugin is not working; there may be problems with your existing configuration.
The error was: None
```

**With answer 2**

```
$ letsencrypt -t -i letsencrypt-icecast:icecast_installer run

How would you like to authenticate with the Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Place files in webroot directory (webroot)
2: Automatically use a temporary webserver (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
The letsencrypt-icecast:icecast_installer plugin is not working; there may be problems with your existing configuration.
The error was: None
```

**With path**

```
$ letsencrypt -t -i letsencrypt-icecast:icecast_installer --letsencrypt-icecast:icecast_installer-configuration_file /home/stations/icecast.xml install --cert-path /etc/letsencrypt/live/icecast/letsencrypt.pem --key-path /etc/letsencrypt/live/icecast/letsencrypt.pem
The letsencrypt-icecast:icecast_installer plugin is not working; there may be problems with your existing configuration.
The error was: None
```

Do you have any idea? Thanks

**Comment by e00E** [comment]
I think youre still in the obtain a certificate phase.
From the readme:
Start lets-encrypt to obtain a certificate however you like for example with letsencrypt --authenticator standalone -d mydomain auth

In this step you dont need this plugin. This plugin is only responsible for installing a certificate you already have into icecast. It still shouldnt break probably but try getting a certificate without the plugin enabled.

**Comment by ChoiZ** [comment]
Thanks for your answer. I've retry with:
letsencrypt --authenticator standalone -d stream.radiozone.fr auth
It's create a folder with this files:
cert.pem
chain.pem
fullchain.pem
privkey.pem

So in my icecast config i've just to add:
<ssl-certificate>/etc/letsencrypt/live/stream.radiozone.fr/privkey.pem</ssl-certificate>
And: 
<listen-socket>
    <ssl>1</ssl>
    <port>443</port>
    <bind-address>my ip address</bind-address>
</listen-socket>
Is it correct ?

**Comment by e00E** [comment]
Now that you have the certificates this plugin should work and do that automatically.
If you want to edit the icecast configuration manually please refer to their documentation (but from memory what you wrote seems ok).

**Comment by ChoiZ** [comment]
Ok thanks I'll try to do it manualy

**Comment by ChoiZ** [comment]
Icecast log say: Invalid cert file /etc/letsencrypt/live/stream.radiozone.fr/privkey.pem
Does privkey.pem must be use for icecast?

Regards,
